### ISSUE TITLE
Dependency problems with gtk2hs-buildtools

### ISSUE THREAD

**Issue by ptkato** [Xandaros/GithubNotify#7]
I'm facing a problem in Arch Linux, trying to install from AUR makes download of `gth2hs-buildtools-0.13.0.5-4`, but it needs the version `0.13.2.1` instead, and it fails to build.

Tried to install `haskell-gtk2hs-buildtools` manually too, but nothing changed.

**Comment by Xandaros** [comment]
I don't have any issues with gtk2hs-buildtools. Can you be a bit more specific about what errors you are getting?

**Comment by ptkato** [comment]
Sure, here's the output:

```
==> Starting build()...
Downloading the latest package list from hackage.haskell.org
Writing a default package environment file to
/home/ptkato/.cache/pacaur/github-notify/src/GithubNotify-0.1.2/cabal.sandbox.config
Using an existing sandbox located at
/home/ptkato/.cache/pacaur/github-notify/src/GithubNotify-0.1.2/.cabal-sandbox
Resolving dependencies...
Notice: installing into a sandbox located at
/home/ptkato/.cache/pacaur/github-notify/src/GithubNotify-0.1.2/.cabal-sandbox
Configuring gtk2hs-buildtools-0.13.2.1...
Failed to install gtk2hs-buildtools-0.13.2.1
Build log ( /home/ptkato/.cache/pacaur/github-notify/src/GithubNotify-0.1.2/.cabal-sandbox/logs/gtk2hs-buildtools-0.13.2.1.log ):
cabal: Entering directory '/tmp/cabal-tmp-27424/gtk2hs-buildtools-0.13.2.1'
Configuring gtk2hs-buildtools-0.13.2.1...
cabal: The program 'alex' version >=3.0.1 is required but it could not be
found.
cabal: Leaving directory '/tmp/cabal-tmp-27424/gtk2hs-buildtools-0.13.2.1'
cabal: Error: some packages failed to install:
cairo-0.13.3.0 depends on gtk2hs-buildtools-0.13.2.1 which failed to install.
gio-0.13.3.0 depends on gtk2hs-buildtools-0.13.2.1 which failed to install.
glib-0.13.4.0 depends on gtk2hs-buildtools-0.13.2.1 which failed to install.
gtk-0.14.5 depends on gtk2hs-buildtools-0.13.2.1 which failed to install.
gtk2hs-buildtools-0.13.2.1 failed during the configure step. The exception
was:
ExitFailure 1
libnotify-0.1.1.0 depends on gtk2hs-buildtools-0.13.2.1 which failed to
install.
pango-0.13.3.0 depends on gtk2hs-buildtools-0.13.2.1 which failed to install.
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build github-notify package(s)
```

**Comment by Xandaros** [comment]
Looks like the problem is that alex is missing.
Try adding alex to the builddepends and see if that helps.

**Comment by ptkato** [comment]
I don't think I'm able to tweak the code neither with `pacaur`, because it just redownloads everything, nor with `makepkg --noextract`, because it just gives another error.

**Comment by Xandaros** [comment]
Oh, I meant adding alex to the PKGBUILD, my bad.
And then don't use noextract :P

**Comment by ptkato** [comment]
Well, I've installed `alex` with pacman and then the build error changed to `happy`, installed it too and the build process went through just fine. I would say that it's worth adding `alex` and `happy` to the depends in the PKGBUILD or cabal.

**Comment by Xandaros** [comment]
Alright, good to know.
I don't think  you actually need them to run github-notify, it should only be necessary to build it, so I'll add it to makedepends.
