### ISSUE TITLE
Unable to build due to compilation error

### ISSUE THREAD

**Issue by ptkato** [Xandaros/GithubNotify#8]
Well, I'm confused, wasn't expecting that, but here it is:

```
src/Main.hs:45:14: error: Not in scope: ‘checkStatus’
```

I've checked the code and couldn't find the source of the error.

**Comment by Xandaros** [comment]
Looks like the newest version of `http-conduit` removed `checkStatus`. There aren't any docs for that version available yet, so for the time being I placed an upper version bound on it and released a new version of `GithubNotify`.

That should build fine now.
